services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: homelab
      POSTGRES_PASSWORD: homelab
      POSTGRES_DB: homelab
    volumes:
    - dbdata:/var/lib/postgresql/data
    networks: [hlab]
    restart: unless-stopped


  backend:
    network_mode: host
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg://homelab:homelab@db:5432/homelab
      SECRET_KEY: "change-me"
    volumes:
    - ./backend:/app
    - config_store:/configs
    - export_store:/exports
    - ./infra/rclone:/rclone
    depends_on: [db]
    networks: [hlab]
    #ports: ["8080:8080"]
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload


volumes:
  dbdata:
  config_store:
  export_store:


networks:
  hlab: